# Generated by Django 4.1.7 on 2023-07-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_entryexitrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='exit_time',
        ),
    ]
