# Generated by Django 4.1.7 on 2023-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
