# Generated by Django 4.1.7 on 2023-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_approved',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_rejected',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
