# Generated by Django 4.1.7 on 2023-08-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
